### ISSUE TITLE
AWS Websocket API

### ISSUE THREAD

**Issue by sitakanttripathy** [villekr/ocpp-serverless-example#1]
Hi Ville, 

am new to OCPP and python but would like to think that I understand what's going on here :). While working on the AWS Websocket Gateway, what's ur thought on the maximum connection duration of 2hrs and how did u go around it.

**Comment by villekr** [comment]
At the moment AWS API Gateway websockets API will not be valid choice for implementing ocpp support. The first reason is the missing support for dynamic connection endpoint urls (see ocpp-j specification "The connection URL" chapter). Also mutual tls authentication is not supported but have to be implemented using lambda authorizers and same goes with password authentication. 2hrs limit is of course inconvenience as well, I really don't know what's the reasoning for that. Anyway, currently thinking this kind of ocpp serverless approach one must implement websockets connection management as a custom service. In the future I hope AWS Websockets API would evolve to support use cases needed to implement ocpp as serverless but it's quite hard to tell what's the backlog and priorization for API Gateway team.

**Comment by sitakanttripathy** [comment]
> At the moment AWS API Gateway websockets API will not be valid choice for implementing ocpp support. The first reason is the missing support for dynamic connection endpoint urls (see ocpp-j specification "The connection URL" chapter). Also mutual tls authentication is not supported but have to be implemented using lambda authorizers and same goes with password authentication. 2hrs limit is of course inconvenience as well, I really don't know what's the reasoning for that. Anyway, currently thinking this kind of ocpp serverless approach one must implement websockets connection management as a custom service. In the future I hope AWS Websockets API would evolve to support use cases needed to implement ocpp as serverless but it's quite hard to tell what's the backlog and priorization for API Gateway team.

@villekr Many thanks for the explanation.
